# Generated by Django 5.2.6 on 2025-11-17 10:34

import cloudinary.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActiviteProfessionnelle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateField()),
                (
                    "date_fin",
                    models.DateField(
                        blank=True,
                        help_text="Laisser vide si en cours ou ponctuel.",
                        null=True,
                    ),
                ),
                (
                    "poste",
                    models.CharField(
                        max_length=255, verbose_name="Poste (Titre du job)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Activité Professionnelle",
                "verbose_name_plural": "Activités Professionnelles",
                "ordering": ["-date_debut"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CompetenceTechnologique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "logo",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        max_length=255,
                        null=True,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp", "svg"]
                            )
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Compétence Technologique",
                "verbose_name_plural": "Compétences Technologiques",
            },
        ),
        migrations.CreateModel(
            name="Diplome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("institution", models.CharField(max_length=200)),
                (
                    "parchemin",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        help_text="Lien vers le PDF ou l'image du diplôme.",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Formation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateField()),
                (
                    "date_fin",
                    models.DateField(
                        blank=True,
                        help_text="Laisser vide si en cours ou ponctuel.",
                        null=True,
                    ),
                ),
                (
                    "titre",
                    models.CharField(
                        max_length=255, verbose_name="Titre (Formation/Diplôme)"
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        max_length=255, verbose_name="Institution (École, Organisme)"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description (Cursus)"),
                ),
                (
                    "justificatif",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        help_text="Upload PDF/Image",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Formation / Diplôme",
                "verbose_name_plural": "Formations / Diplômes",
                "ordering": ["-date_debut"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PosteCible",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Poste Ciblé",
                "verbose_name_plural": "Postes Ciblés",
            },
        ),
        migrations.CreateModel(
            name="Presentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texte", models.TextField()),
                ("nom", models.CharField(default="John", max_length=100)),
                ("prenom", models.CharField(default="Doe", max_length=100)),
                (
                    "email",
                    models.EmailField(default="john.doe@example.com", max_length=254),
                ),
                (
                    "photo",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        max_length=255,
                        null=True,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png", "webp"]
                            )
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "Texte de Présentation",
                "verbose_name_plural": "Texte de Présentation",
            },
        ),
        migrations.CreateModel(
            name="ServiceCivique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateField()),
                (
                    "date_fin",
                    models.DateField(
                        blank=True,
                        help_text="Laisser vide si en cours ou ponctuel.",
                        null=True,
                    ),
                ),
                (
                    "mission",
                    models.CharField(max_length=255, verbose_name="Mission (Titre)"),
                ),
                ("organisme_accueil", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Service Civique",
                "verbose_name_plural": "Services Civiques",
                "ordering": ["-date_debut"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MissionActivitePro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sous_titre", models.CharField(max_length=255)),
                (
                    "descriptions",
                    models.TextField(
                        blank=True,
                        help_text="Un point par ligne. Chaque ligne deviendra une puce.",
                    ),
                ),
                (
                    "activite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missions",
                        to="api.activiteprofessionnelle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mission (Activité Pro)",
            },
        ),
        migrations.CreateModel(
            name="ProjetEtudiant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateField()),
                (
                    "date_fin",
                    models.DateField(
                        blank=True,
                        help_text="Laisser vide si en cours ou ponctuel.",
                        null=True,
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                (
                    "introduction",
                    models.TextField(verbose_name="Introduction (Description)"),
                ),
                ("role", models.CharField(blank=True, max_length=255)),
                (
                    "media_video",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        help_text="Vidéo unique de démonstration",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "url_code_source",
                    models.URLField(
                        blank=True,
                        help_text="Lien vers le dépôt GitHub, GitLab, etc.",
                        max_length=500,
                        null=True,
                        verbose_name="Lien Code Source",
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Institution (Cadre scolaire)",
                    ),
                ),
                (
                    "technologies",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Sélectionnez les technologies utilisées",
                        related_name="%(class)s_projets",
                        to="api.competencetechnologique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projet Étudiant",
                "verbose_name_plural": "Projets Étudiants",
                "ordering": ["-date_debut"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MediaProjetEtudiant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", cloudinary.models.CloudinaryField(max_length=255)),
                ("legende", models.CharField(blank=True, max_length=255)),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_photos",
                        to="api.projetetudiant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Média (Photo Projet Étudiant)",
            },
        ),
        migrations.CreateModel(
            name="ProjetPersonnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateField()),
                (
                    "date_fin",
                    models.DateField(
                        blank=True,
                        help_text="Laisser vide si en cours ou ponctuel.",
                        null=True,
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                (
                    "introduction",
                    models.TextField(verbose_name="Introduction (Description)"),
                ),
                ("role", models.CharField(blank=True, max_length=255)),
                (
                    "media_video",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        help_text="Vidéo unique de démonstration",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "url_code_source",
                    models.URLField(
                        blank=True,
                        help_text="Lien vers le dépôt GitHub, GitLab, etc.",
                        max_length=500,
                        null=True,
                        verbose_name="Lien Code Source",
                    ),
                ),
                (
                    "technologies",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Sélectionnez les technologies utilisées",
                        related_name="%(class)s_projets",
                        to="api.competencetechnologique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projet Personnel",
                "verbose_name_plural": "Projets Personnels",
                "ordering": ["-date_debut"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MediaProjetPersonnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", cloudinary.models.CloudinaryField(max_length=255)),
                ("legende", models.CharField(blank=True, max_length=255)),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_photos",
                        to="api.projetpersonnel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Média (Photo Projet Perso)",
            },
        ),
        migrations.CreateModel(
            name="ProjetProfessionnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateField()),
                (
                    "date_fin",
                    models.DateField(
                        blank=True,
                        help_text="Laisser vide si en cours ou ponctuel.",
                        null=True,
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                (
                    "introduction",
                    models.TextField(verbose_name="Introduction (Description)"),
                ),
                ("role", models.CharField(blank=True, max_length=255)),
                (
                    "media_video",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        help_text="Vidéo unique de démonstration",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "url_code_source",
                    models.URLField(
                        blank=True,
                        help_text="Lien vers le dépôt GitHub, GitLab, etc.",
                        max_length=500,
                        null=True,
                        verbose_name="Lien Code Source",
                    ),
                ),
                (
                    "technologies",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Sélectionnez les technologies utilisées",
                        related_name="%(class)s_projets",
                        to="api.competencetechnologique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projet Professionnel",
                "verbose_name_plural": "Projets Professionnels",
                "ordering": ["-date_debut"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MediaProjetProfessionnel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", cloudinary.models.CloudinaryField(max_length=255)),
                ("legende", models.CharField(blank=True, max_length=255)),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_photos",
                        to="api.projetprofessionnel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Média (Photo Projet Pro)",
            },
        ),
        migrations.CreateModel(
            name="MissionServiceCivique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sous_titre", models.CharField(max_length=255)),
                (
                    "descriptions",
                    models.TextField(
                        blank=True,
                        help_text="Un point par ligne. Chaque ligne deviendra une puce.",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="missions",
                        to="api.servicecivique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mission (Service Civique)",
            },
        ),
        migrations.CreateModel(
            name="TravailEffectueProjetEtu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sous_titre", models.CharField(max_length=255)),
                (
                    "descriptions",
                    models.TextField(
                        blank=True,
                        help_text="Un point par ligne. Chaque ligne deviendra une puce.",
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travail_effectue",
                        to="api.projetetudiant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Travail Effectué (Projet Étudiant)",
            },
        ),
        migrations.CreateModel(
            name="TravailEffectueProjetPerso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sous_titre", models.CharField(max_length=255)),
                (
                    "descriptions",
                    models.TextField(
                        blank=True,
                        help_text="Un point par ligne. Chaque ligne deviendra une puce.",
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travail_effectue",
                        to="api.projetpersonnel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Travail Effectué (Projet Perso)",
            },
        ),
        migrations.CreateModel(
            name="TravailEffectueProjetPro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sous_titre", models.CharField(max_length=255)),
                (
                    "descriptions",
                    models.TextField(
                        blank=True,
                        help_text="Un point par ligne. Chaque ligne deviendra une puce.",
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travail_effectue",
                        to="api.projetprofessionnel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Travail Effectué (Projet Pro)",
            },
        ),
    ]
