# Generated by Django 5.2.6 on 2025-11-18 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionCompetence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(
                        max_length=100, verbose_name="Titre de la section"
                    ),
                ),
                (
                    "ordre",
                    models.IntegerField(
                        default=0,
                        help_text="Ordre d'affichage (plus petit = plus haut)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Section de Compétences",
                "verbose_name_plural": "Sections de Compétences",
                "ordering": ["ordre"],
            },
        ),
        migrations.RemoveField(
            model_name="presentation",
            name="texte",
        ),
        migrations.AddField(
            model_name="presentation",
            name="description",
            field=models.TextField(default=0, verbose_name="Description détaillée"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="presentation",
            name="sous_titre",
            field=models.CharField(
                default="Développeur Passionné",
                max_length=255,
                verbose_name="Sous-titre / Accroche",
            ),
        ),
        migrations.AddField(
            model_name="competencetechnologique",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="competences",
                to="api.sectioncompetence",
                verbose_name="Section / Catégorie",
            ),
        ),
    ]
