# Generated by Django 5.2.6 on 2025-11-18 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_sectioncompetence_remove_presentation_texte_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="presentation",
            name="description",
        ),
        migrations.RemoveField(
            model_name="presentation",
            name="sous_titre",
        ),
        migrations.CreateModel(
            name="SousTitrePresentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titre",
                    models.CharField(
                        max_length=255, verbose_name="Sous-titre / Accroche"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description détaillée")),
                (
                    "ordre",
                    models.IntegerField(default=0, help_text="Ordre d'affichage"),
                ),
                (
                    "presentation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="api.presentation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Détail de Présentation",
                "verbose_name_plural": "Détails de Présentation",
                "ordering": ["ordre"],
            },
        ),
    ]
