# Generated by Django 5.2.6 on 2025-11-19 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_presentation_description_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="missionservicecivique",
            name="service",
        ),
        migrations.RemoveField(
            model_name="travaileffectueprojetetu",
            name="projet",
        ),
        migrations.RemoveField(
            model_name="travaileffectueprojetperso",
            name="projet",
        ),
        migrations.RemoveField(
            model_name="travaileffectueprojetpro",
            name="projet",
        ),
        migrations.CreateModel(
            name="DetailEvenement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "sous_titre",
                    models.CharField(
                        max_length=255, verbose_name="Sous-titre / Intitulé"
                    ),
                ),
                (
                    "descriptions",
                    models.TextField(
                        blank=True,
                        help_text="Un point par ligne. Chaque ligne deviendra une puce dans l'affichage.",
                    ),
                ),
                (
                    "ordre",
                    models.IntegerField(default=0, help_text="Ordre d'affichage"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Détail / Mission",
                "verbose_name_plural": "Détails & Missions",
                "ordering": ["ordre"],
            },
        ),
        migrations.DeleteModel(
            name="MissionActivitePro",
        ),
        migrations.DeleteModel(
            name="MissionServiceCivique",
        ),
        migrations.DeleteModel(
            name="TravailEffectueProjetEtu",
        ),
        migrations.DeleteModel(
            name="TravailEffectueProjetPerso",
        ),
        migrations.DeleteModel(
            name="TravailEffectueProjetPro",
        ),
    ]
