# Generated by Django 5.2.6 on 2025-09-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_populate_projects"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="video_url",
        ),
        migrations.AddField(
            model_name="project",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="project_videos/"),
        ),
    ]
