# Generated by Django 5.2.6 on 2025-12-03 10:52

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_missionservicecivique_service_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mediaprojetpersonnel",
            name="projet",
        ),
        migrations.RemoveField(
            model_name="mediaprojetprofessionnel",
            name="projet",
        ),
        migrations.RemoveField(
            model_name="projetetudiant",
            name="technologies",
        ),
        migrations.RemoveField(
            model_name="projetpersonnel",
            name="technologies",
        ),
        migrations.RemoveField(
            model_name="projetprofessionnel",
            name="technologies",
        ),
        migrations.AlterModelOptions(
            name="activiteprofessionnelle",
            options={
                "ordering": ["-date_debut"],
                "verbose_name": "Activité Pro",
                "verbose_name_plural": "Activités Pro",
            },
        ),
        migrations.AlterModelOptions(
            name="formation",
            options={"ordering": ["-date_debut"]},
        ),
        migrations.AlterModelOptions(
            name="postecible",
            options={},
        ),
        migrations.AlterModelOptions(
            name="presentation",
            options={"verbose_name": "Profil", "verbose_name_plural": "Profil"},
        ),
        migrations.AlterModelOptions(
            name="soustitrepresentation",
            options={"ordering": ["ordre"]},
        ),
        migrations.AlterField(
            model_name="activiteprofessionnelle",
            name="date_fin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="activiteprofessionnelle",
            name="poste",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="competencetechnologique",
            name="logo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="competencetechnologique",
            name="section",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="competences",
                to="api.sectioncompetence",
            ),
        ),
        migrations.AlterField(
            model_name="detailevenement",
            name="descriptions",
            field=models.TextField(blank=True, help_text="Un point par ligne."),
        ),
        migrations.AlterField(
            model_name="detailevenement",
            name="ordre",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="diplome",
            name="parchemin",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="formation",
            name="date_fin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="formation",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="formation",
            name="institution",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="formation",
            name="justificatif",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="formation",
            name="titre",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="presentation",
            name="photo",
            field=cloudinary.models.CloudinaryField(
                blank=True, max_length=255, null=True, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="sectioncompetence",
            name="ordre",
            field=models.IntegerField(default=0, help_text="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name="servicecivique",
            name="date_fin",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="servicecivique",
            name="mission",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="soustitrepresentation",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="soustitrepresentation",
            name="ordre",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="soustitrepresentation",
            name="titre",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="Projet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("PRO", "Professionnel"),
                            ("ETU", "Étudiant"),
                            ("PERSO", "Personnel"),
                        ],
                        default="PERSO",
                        max_length=10,
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("introduction", models.TextField(verbose_name="Description courte")),
                ("role", models.CharField(blank=True, max_length=255)),
                (
                    "institution",
                    models.CharField(
                        blank=True, help_text="Entreprise ou École", max_length=255
                    ),
                ),
                (
                    "media_video",
                    cloudinary.models.CloudinaryField(
                        blank=True, max_length=255, null=True, verbose_name="video"
                    ),
                ),
                (
                    "url_code_source",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "technologies",
                    models.ManyToManyField(
                        blank=True,
                        related_name="projets",
                        to="api.competencetechnologique",
                    ),
                ),
            ],
            options={
                "verbose_name": "Projet",
                "verbose_name_plural": "Projets",
                "ordering": ["-date_debut"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MediaProjet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        max_length=255, verbose_name="image"
                    ),
                ),
                ("legende", models.CharField(blank=True, max_length=255)),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_photos",
                        to="api.projet",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="MediaProjetEtudiant",
        ),
        migrations.DeleteModel(
            name="MediaProjetPersonnel",
        ),
        migrations.DeleteModel(
            name="MediaProjetProfessionnel",
        ),
        migrations.DeleteModel(
            name="ProjetEtudiant",
        ),
        migrations.DeleteModel(
            name="ProjetPersonnel",
        ),
        migrations.DeleteModel(
            name="ProjetProfessionnel",
        ),
    ]
