# Generated by Django 5.2.6 on 2025-09-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_project_video_url_project_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetenceTechnologique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="competences_logos/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Compétence Technologique",
                "verbose_name_plural": "Compétences Technologiques",
            },
        ),
        migrations.CreateModel(
            name="Diplome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                ("institution", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Parcours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("poste", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
                ("periode", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Parcours",
                "verbose_name_plural": "Parcours",
                "ordering": ["-periode"],
            },
        ),
        migrations.CreateModel(
            name="PosteCible",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Poste Ciblé",
                "verbose_name_plural": "Postes Ciblés",
            },
        ),
        migrations.CreateModel(
            name="Presentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texte", models.TextField()),
            ],
            options={
                "verbose_name": "Texte de Présentation",
                "verbose_name_plural": "Texte de Présentation",
            },
        ),
    ]
