# Generated by Django 5.2.6 on 2025-12-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_mediaprojetpersonnel_projet_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projet",
            name="media_video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="projets_videos",
                verbose_name="Vidéo (MP4, WebM)",
            ),
        ),
    ]
