# Generated by Django 5.2.6 on 2025-12-09 16:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_projet_media_video"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projet",
            old_name="url_code_source",
            new_name="de_source",
        ),
        migrations.AlterField(
            model_name="projet",
            name="media_video",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Vidéo unique de démonstration",
                max_length=255,
                null=True,
            ),
        ),
    ]
