# Generated by Django 5.2.6 on 2025-10-06 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_competencetechnologique_diplome_parcours_postecible_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="architecture_projet",
        ),
        migrations.RemoveField(
            model_name="project",
            name="role_personnel",
        ),
        migrations.RemoveField(
            model_name="project",
            name="specificites_competences",
        ),
        migrations.AddField(
            model_name="project",
            name="source_code_zip",
            field=models.FileField(
                blank=True,
                help_text="Archive ZIP du code source.",
                null=True,
                upload_to="project_sources/",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tasks_effectuees",
            field=models.TextField(
                default="", help_text="Décrivez les tâches générales effectuées."
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="project",
            name="technologies",
        ),
        migrations.CreateModel(
            name="WorkDone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subtitle", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_done",
                        to="api.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="technologies",
            field=models.ManyToManyField(
                related_name="projects", to="api.competencetechnologique"
            ),
        ),
    ]
