# Generated by Django 5.2.6 on 2025-10-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_remove_project_architecture_projet_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Message de Contact",
                "verbose_name_plural": "Messages de Contact",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="parcours",
            name="description",
            field=models.CharField(max_length=300),
        ),
    ]
