# Generated by Django 5.2.6 on 2026-01-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_rename_url_code_source_projet_de_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activiteprofessionnelle",
            name="type_contrat",
            field=models.CharField(
                choices=[
                    ("SALARIE", "Salarié (CDI/CDD)"),
                    ("FREELANCE", "Freelance / Indépendant"),
                ],
                default="SALARIE",
                max_length=20,
                verbose_name="Type de Contrat",
            ),
        ),
        migrations.AlterField(
            model_name="projet",
            name="categorie",
            field=models.CharField(
                choices=[
                    ("PRO", "Professionnel"),
                    ("ETU", "Étudiant"),
                    ("PERSO", "Personnel"),
                    ("FREELANCE", "Projet Freelance"),
                ],
                default="PERSO",
                max_length=10,
            ),
        ),
    ]
