# Generated by Django 5.2.6 on 2025-10-10 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_contactmessage_alter_parcours_description"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ContactMessage",
        ),
        migrations.AddField(
            model_name="presentation",
            name="email",
            field=models.EmailField(default="john.doe@example.com", max_length=254),
        ),
        migrations.AddField(
            model_name="presentation",
            name="nom",
            field=models.CharField(default="John", max_length=100),
        ),
        migrations.AddField(
            model_name="presentation",
            name="photo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="photos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="presentation",
            name="prenom",
            field=models.CharField(default="Doe", max_length=100),
        ),
        migrations.AlterField(
            model_name="competencetechnologique",
            name="logo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="competences_logos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp", "svg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="parcours",
            name="description",
            field=models.CharField(max_length=200),
        ),
    ]
