# Generated by Django 5.2.6 on 2025-11-11 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_delete_contactmessage_presentation_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workdone",
            name="project",
        ),
        migrations.CreateModel(
            name="Projet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=200)),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="project_videos/"
                    ),
                ),
                ("description", models.TextField()),
                (
                    "tasks_effectuees",
                    models.TextField(
                        help_text="Décrivez les tâches générales effectuées."
                    ),
                ),
                (
                    "zip_code_source",
                    models.FileField(
                        blank=True,
                        help_text="Archive ZIP du code source.",
                        null=True,
                        upload_to="project_sources/",
                    ),
                ),
                (
                    "technologies",
                    models.ManyToManyField(
                        related_name="projets", to="api.competencetechnologique"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TravailEffectue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sous_titre", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travaux_effectues",
                        to="api.projet",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="WorkDone",
        ),
    ]
