# Generated by Django 5.2.6 on 2025-11-14 17:52

import cloudinary.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_remove_workdone_project_projet_travaileffectue_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvenementChronologique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titre", models.CharField(max_length=255, verbose_name="Titre")),
                ("date_debut", models.DateField()),
                (
                    "date_fin",
                    models.DateField(
                        blank=True,
                        help_text="Laisser vide si en cours ou ponctuel.",
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Etudes", "Études"),
                            ("Diplome", "Diplôme"),
                            ("Service civique", "Service civique"),
                            ("Projets Etudiant", "Projets Étudiant"),
                            ("Projets Professionnels", "Projets Professionnels"),
                            ("Projets Personnels", "Projets Personnels"),
                            ("Activité rémunératrice", "Activité rémunératrice"),
                        ],
                        default="Projets Professionnels",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Utilisé comme introduction pour les projets.",
                        verbose_name="Description (Introduction)",
                    ),
                ),
                (
                    "specificites",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Données variables selon le type (voir documentation de la structure)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement Chronologique",
                "verbose_name_plural": "Événements Chronologiques",
                "ordering": ["-date_debut"],
            },
        ),
        migrations.DeleteModel(
            name="Parcours",
        ),
        migrations.RemoveField(
            model_name="travaileffectue",
            name="projet",
        ),
        migrations.AddField(
            model_name="diplome",
            name="parchemin",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Lien vers le PDF ou l'image du diplôme.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="competencetechnologique",
            name="logo",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp", "svg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="presentation",
            name="photo",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    )
                ],
            ),
        ),
        migrations.DeleteModel(
            name="Projet",
        ),
        migrations.DeleteModel(
            name="TravailEffectue",
        ),
    ]
