# Generated by Django 5.2.6 on 2025-11-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_activiteprofessionnelle_formation_and_more"),
    ]

    operations = [
        # Ajoute la colonne manquante à ProjetProfessionnel
        migrations.AddField(
            model_name="projetprofessionnel",
            name="url_code_source",
            field=models.URLField(
                blank=True,
                help_text="Lien vers le dépôt GitHub, GitLab, etc.",
                max_length=500,
                null=True,
                verbose_name="Lien Code Source",
            ),
        ),
        # Ajoute la colonne manquante à ProjetEtudiant
        migrations.AddField(
            model_name="projetetudiant",
            name="url_code_source",
            field=models.URLField(
                blank=True,
                help_text="Lien vers le dépôt GitHub, GitLab, etc.",
                max_length=500,
                null=True,
                verbose_name="Lien Code Source",
            ),
        ),
        # Ajoute la colonne manquante à ProjetPersonnel
        migrations.AddField(
            model_name="projetpersonnel",
            name="url_code_source",
            field=models.URLField(
                blank=True,
                help_text="Lien vers le dépôt GitHub, GitLab, etc.",
                max_length=500,
                null=True,
                verbose_name="Lien Code Source",
            ),
        ),
    ]